### PR TITLE
update dependencies and code

### PR DESCRIPTION
**Pull request by milahu**

### CODE REVIEW

**Comment by milahu** [comment]
this repo looks abandoned, patch merged in https://github.com/milahu/d3-fdg-svelte

**Comment by happybeing** [comment]
Thanks for the PR, it's great you've found it useful and updated it. It's not something I'm actively working on but I was planning to review and merge, but I'm also happy if you want to build on this and take the lead.

**Review by happybeing — APPROVED** [review]
All good.

**Comment by milahu** [comment]
thanks : )

can you deploy the demo to gh-pages? like ...

```
npm run build
cp -r public ../temp-public
git checkout --orphan gh-pages
git rm -rf --dry-run . # preview delete
git rm -rf .
mv ../temp-public/* ./
rmdir ../temp-public
git commit -a -m 'init gh-pages'
git push origin
```

**Comment by happybeing** [comment]
Something not quite right I think as nothing is being committed:
```sh
$ git commit -a -m 'init gh-pages'
On branch gh-pages

Initial commit

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	build/
	bundle.css
	bundle.css.map
	bundle.js
	bundle.js.map
	favicon.png
	global.css
	index.html
	node_modules/
	public/

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by milahu** [comment]
```
git add build index.html global.css
git commit -m 'init gh-pages'
```

**Comment by happybeing** [comment]
Done thanks, see: https://happybeing.github.io/d3-fdg-svelte/

**Pull request merged**
